"""empty message

Revision ID: 9288c07466b0
Revises: db4a3666a022
Create Date: 2023-03-28 12:40:45.906496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9288c07466b0'
down_revision = 'db4a3666a022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'account', ['player_two_id'], ['id'])
        batch_op.create_foreign_key(None, 'result', ['result_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['player_one_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)

    # ### end Alembic commands ###
